### ISSUE TITLE
Running this in cordova

### ISSUE THREAD

**Issue by KiranShahdadpuri** [NiklasMerz/fingerprint-aio-demo#3]
How can I open this project in cordova and run it?

**Comment by NiklasMerz** [comment]
You clone this repo and go to the new directory with bash/cmd/powershell etc. You can run this porject using cordova cli e.g. `cordova run android`.

If you have further questions please ask me on [gitter](https://gitter.im/cordova-plugin-fingerprint-aio/Lobby). I closing this issue now since this is more of a question.
